# Copyright 2015 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: custom
env: flex

handlers:
  - url: /docs
    static_files: docs/index.html
    upload: docs/index.html
  - url: /docs/(.*)
    static_files: docs/\1
    upload: docs/.
  - url: /.*
    script: this field is required, but ignored
    secure: always

endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy openapi.yaml' command.
  name: "ben-gtest.appspot.com"
  config_id: "2017-12-22r1"
